name: react_animations
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
dev_dependencies:
  autoprefixer_transformer: ^0.2.1
  react: ^0.6.2
  sass: ^0.4.2
transformers:
  - sass
  - autoprefixer_transformer
